version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: task-python:latest
    environment:
      - PYTHONPATH=/app
    command: python app/main.py
    volumes:
      - .:/app
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - my-network

  test:
    build:
      context: .
      dockerfile: Dockerfile
    image: task-python:latest
    environment:
      - PYTHONPATH=/app
    command: python tests/test_main.py
    volumes:
      - .:/app
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - my-network

networks:
  my-network:
    driver: overlay
    attachable: true
