apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: task-python
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/saiaryansahoo/tanX.fi-Task-DevOps'
    targetRevision: main
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
